---
title: "homework4"
author: "mingyue hu"
date: "11/1/2022"
output:
  word_document: default
  pdf_document: default
---



###  Part 1
#Question 1(a)
```{r}
salmon <- read.csv("salmon.csv")

initvals <- lm( I(1/salmon$recruits)~I(1/salmon$spawners))
result1 <- summary(initvals)$coef[,"Estimate"]
result1
```


#Question 1(b)
```{r}
func1 <- function(par, S ){
	1/(par[1] + par[2]/S)
}

func2 <- function(par, S){
	mu <- 1/(par[1] + par[2]/S)
	cbind(-mu^2, -mu^2*1/S)
}

func3 <- function(par,S,theta){
	1/(par[1] + par[2]/S)
}
source("glsfunctions.R")
glsoutput <- glsiter(result1, func1, func3, func2, theta=1,  salmon$recruits,  salmon$spawners, 5)
glsest <- glsoutput[[1]]
glsvcov <- glsoutput[[3]]
glsest
glsse<-sqrt(diag(glsvcov))
glsse
```


#Question 1(c)
```{r}
est<-1/glsest[1]
se<-est^2*glsse[1]
intgamma <- cbind(est-1.96*se,est +1.96*se)
intgamma
```


#Question 2
```{r}
gammafit <- glm(recruits~I(1/spawners), data = salmon, family = Gamma(link = "inverse"))
summary(gammafit)
```


#Question 3
```{r}
muhatinit <-  func1(result1, salmon$spawners)

plot(salmon$spawners, salmon$recruits, xlab = "Spawners", ylab = "Recruits", main = "Data with Estimated Expectation Function")
lines(salmon$spawners[order(salmon$spawners)], muhatinit[order(salmon$spawners)])

plot(muhatinit,(salmon$recruits - muhatinit)/muhatinit, xlab = expression(hat(mu)), ylab = "Residual", main = "Additive error model")

plot(muhatinit, residuals(gammafit, type = "deviance"), xlab = expression(hat(mu)), ylab = "Residual", main = "GLM")
```


###  Part 2
#Question 1
```{r}
beta0 <- 0.9
beta1 <- 1.3

ages <- rep(seq(1, 12, by =  1) , each = 3)

Y <- beta0*ages^(beta1) + 0.2*(beta0*ages^(beta1))^(1.25)*rnorm(length(ages), 0,1)
plot(ages,Y)
```


#Question 4
```{r}
source("glsfunctions.R")
source("gfunctionsforFishExample.R")

### Helper function for GLS with known/fixed weights
quadformknownw <- function(par, w, Y, ages){
  sum((Y - par[2]*ages^par[1])^2*w)
}
beta0 <- 0.9
beta1 <- 1.3

ages <- rep(seq(1, 12, by =  1) , each = 3)

iter <- 0

betahatUs <- c()
betahatTs <- c()
betahatGs <- c()

repeat{
  
iter <- iter + 1
 

####  Code to simulate data from true model
Y <- beta0*ages^(beta1) + 0.2*(beta0*ages^(beta1))^(1.25)*rnorm(length(ages), 0,1)
lminit <- summary(lm(log(Y[Y>0])~log(ages[Y>0])))$coef
coefinit <- c(lminit[2], exp(lminit[1]))
#### Code to estimate model using GLS with estimated weights and a power of 0.75
Si2 <- tapply(Y, ages, var)
wgts <- rep(1/Si2, each = 3)
######  The sample code had a mistake for the starting values for betahatU  ###### 
betahatU <- optim(c(lminit[2], exp(lminit[1])),  quadformknownw, w= wgts, Y=Y, ages=ages)$par

#### Code to estimate model using a power of 1.25
betahatT <- glsiter(coefinit, g1fun, g2fun, derfun, 1.25, Y, ages, 5)[[1]] 

#### Code to estimate model using a power of 1:
betahatG <- glsiter(coefinit, g1fun, g2fun, derfun, 1 , Y, ages, 5)[[1]] 


betahatUs <- rbind(betahatUs, as.vector(betahatU))
betahatGs <- rbind(betahatGs, as.vector(betahatG))
betahatTs <- rbind(betahatTs, as.vector(betahatT))
if(iter == 500){break}


}
bU <- apply(betahatUs, 2, mean) - c(beta1, beta0)
bG <- apply(betahatGs, 2, mean) - c(beta1, beta0)
bT <- apply(betahatTs, 2, mean) - c(beta1, beta0)

vU <- apply(betahatUs, 2, var)
vG <- apply(betahatGs, 2, var)
vT <- apply(betahatTs, 2, var)

#### Note: defining or calculating MSE as variance plus squared bias is also correct
mU <- apply((t(betahatUs) - c(beta1, beta0))^2 , 1, mean)
mG <- apply((t(betahatGs) -  c(beta1, beta0))^2 , 1, mean)  
mT <- apply((t(betahatTs) -  c(beta1, beta0))^2 , 1, mean)


cbind(rbind(bU, bG, bT), rbind(vU, vG, vT), rbind(mU, mG, mT))


```
```{r}
iter <- 0

betahatUs <- c()
betahatTs <- c()
betahatGs <- c()

repeat{
  
iter <- iter + 1
 

####  Code to simulate data from true model
Y <- beta0*ages^(beta1) + 0.2*(beta0*ages^(beta1))^(1.25)*rnorm(length(ages), 0,1)
lminit <- summary(lm(log(Y[Y>0])~log(ages[Y>0])))$coef
coefinit <- c(lminit[2], exp(lminit[1]))
#### Code to estimate model using GLS with estimated weights and a power of 0.75
Si2 <- tapply(Y, ages, var)
wgts <- rep(1/Si2, each = 3)
######  The sample code had a mistake for the starting values for betahatU  ###### 
betahatU <- optim(c(lminit[2], exp(lminit[1])),  quadformknownw, w= wgts, Y=Y, ages=ages)$par

#### Code to estimate model using a power of 1.25
betahatT <- glsiter(coefinit, g1fun, g2fun, derfun, 1.25, Y, ages, 5)[[1]] 

#### Code to estimate model using a power of 1:
betahatG <- glsiter(coefinit, g1fun, g2fun, derfun, 1 , Y, ages, 5)[[1]] 


betahatUs <- rbind(betahatUs, as.vector(betahatU))
betahatGs <- rbind(betahatGs, as.vector(betahatG))
betahatTs <- rbind(betahatTs, as.vector(betahatT))
if(iter == 5000){break}


}
bU <- apply(betahatUs, 2, mean) - c(beta1, beta0)
bG <- apply(betahatGs, 2, mean) - c(beta1, beta0)
bT <- apply(betahatTs, 2, mean) - c(beta1, beta0)

vU <- apply(betahatUs, 2, var)
vG <- apply(betahatGs, 2, var)
vT <- apply(betahatTs, 2, var)
#### Note: defining or calculating MSE as variance plus squared bias is also correct
mU <- apply((t(betahatUs) - c(beta1, beta0))^2 , 1, mean)
mG <- apply((t(betahatGs) -  c(beta1, beta0))^2 , 1, mean)  
mT <- apply((t(betahatTs) -  c(beta1, beta0))^2 , 1, mean)


cbind(rbind(bU, bG, bT), rbind(vU, vG, vT), rbind(mU, mG, mT))
```



### part 3
```{r}
gulls <- read.csv("gullsdata2020-1.csv")
Y <- gulls$oxy
X <- gulls$bm
o <- glm(Y ~ X, family = Gamma(link = "log"))
summary(o)
a_hat<-1/summary(o)$dispersion;a_hat
o$coefficients[1]
mu<-exp(o$coefficients[1] + o$coefficients[2] * 1700);mu
b_hat<-mu/a_hat;b_hat
qhat<-1 - pgamma(6, shape = 1.17, scale = 20.08);qhat
# Bootstrap 95% CI for Probability (Y>6|X=1700)
# function to obtain Probability from the data

B <- 5000
b <- 0 
qhatstarBs <- c()
gammafit <- glm(Y ~ X, family = Gamma(link = "log"))
repeat{

b<-b+1
Ystar <- simulate(gammafit)
gammafitstar <- glm(Ystar$sim_1~X, family = Gamma(link = "log")) 
shapestar <- 1/summary(gammafitstar)$dispersion
mustar <- exp(gammafitstar$coef[1] + gammafitstar$coef[2]*1700) 
scalestar <- mustar/shapestar
qhatstarBs <-  c(qhatstarBs,1 - pgamma(6,shape = shapestar, scale = scalestar))
if(b == B){break} 
}

 lowerEndpoint <- qhat^2/quantile(qhatstarBs, prob = 0.975) 
 upperEndpoint <- qhat^2/quantile(qhatstarBs, prob = 0.025) 
 c(lowerEndpoint, upperEndpoint)

 c(quantile(qhatstarBs, prob = 0.025), quantile(qhatstarBs, prob = 0.975))
```











